apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: teama
  namespace: argocd
spec:
  description: Team A applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: team-a
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'